// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Apps.Leaderboards.Database;

#nullable disable

namespace Web.Apps.Migrations
{
    [DbContext(typeof(LeaderboardDatabase))]
    partial class LeaderboardDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Web.Apps.Leaderboards.Database.Scores.TopScoresDbEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scores")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TopScores");
                });
#pragma warning restore 612, 618
        }
    }
}
